background {
    path = /home/chef_carthy/.config/chef-os/wallpapers/chefos-main.png
    color = rgb(F1EBDD)
}

label {
    text = cmd[update:1000] echo "$(date +'\''%H:%M'\'')"
    font_family = Noto Sans
    font_size = 64
    color = rgb(2B2A28)
    position = 0, 60
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] echo "$(date +'\''%A, %B %d'\'')"
    font_family = Noto Sans
    font_size = 16
    color = rgb(6E6A5F)
    position = 0, -10
    halign = center
    valign = center
}

input-field {
    size = 260, 48
    outline_thickness = 1
    outer_color = rgb(DCD3BE)
    inner_color = rgb(F8F4EA)
    font_color = rgb(2B2A28)
    placeholder_text = <span>Password</span>
    position = 0, -140
    halign = center
    valign = center
}