preload = /home/chef_carthy/.config/chef-os/wallpapers/chefos-main.png

wallpaper {
    monitor = Virtual-1
    path = /home/chef_carthy/.config/chef-os/wallpapers/chefos-main.png
    fit_mode = cover
}

splash = false
ipc = on